apiVersion: v1
kind: Pod
metadata:
  name: my-python-app
  labels:
    app: python-web
spec:
  containers:
  - name: python-container
    image: tiangolo/uwsgi-nginx-flask:python3.8
    ports:
    - containerPort: 80
